### ISSUE TITLE
Unable to install multiple Weaviate clusters in same namespace

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate-helm#115]
The templates hardcode a resource name instead of relying on the helm release name. So when you try to deploy another weaviate cluster it would fail because there is already a statefulset named weaviate.

I propose to instead use this format for all resources:
```
kind: StatefulSet     
metadata:     
  name: "{{ .Release.Name }}-weaviate"     
  labels:                                                                                                             
    name: "{{ .Release.Name }}-weaviate"                                                                          
    app: "{{ .Release.Name }}-weaviate"                                                                          
    app.kubernetes.io/name: "{{ .Release.Name }}-weaviate"                                                     
    app.kubernetes.io/managed-by: helm                         
    app.kubernetes.io/component: database                       
    app.kubernetes.io/version: "{{ .Values.image.tag }}"
```
