### ISSUE TITLE
Missing service definition for metrics/prometheus endpoint

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate-helm#121]
Prometheus by default is exposed on port 2112 when `env.PROMETHEUS_MONITORING_ENABLED: true`. However the weaviate service definition has a hardcoded targetport of 8080. So either the weaviate service should also expose the prometheus service or we should create a new service definition for prometheus.

**Comment by samos123** [comment]
actually it makes sense the way it is, because each weaviate replica will have it's own metric endpoitn accessible under weaviate-$X:2112/metrics  .  I will close the bug

**Comment by jfcmartins** [comment]
Hey @samos123 👋 I came across the same issue and I don't understand when you say that makes sense the way it is. The `targetPort` is hardcoded to `8080`, so the metrics will not be available for Prometheus to scrape in the Weaviate Service. 

What solves this issue is to change the Service ports spec to this:
```yaml
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 2112
      targetPort: 2112
```

Am I missing something?
