### ISSUE TITLE
HTTP Bearer Token Authentication Broken with Version 1.19.0

### ISSUE THREAD

**Issue by tsafs** [weaviate/weaviate-helm#146]
Hi :) 

It seems that the authentication via API key does not work as expected anymore with **weaviate 1.19.0**.

Authentication does not work properly, regardless whether I configure the authentication settings via the config map or environment variables as shown below.

**via config map**:
```
authentication:
    apikey:
      enabled: true
      allowed_keys:
        - 336c66524e5172726d6243334d46784e
      users:
        - irrelevantUserName
    anonymous_access:
      enabled: false
```
**via environmental variables**:
``` 
env:
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
  AUTHENTICATION_APIKEY_ENABLED: 'true'
  AUTHENTICATION_APIKEY_USERS: 'irrelevantUserName'
envSecrets:
  AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'weaviate-api-key-secret'
```

**Observed Issue:**

When I submit a `GET` request to weaviate **without** the `Authorization: Bearer <weaviate-api-key-secret>` header set, my request goes through.

This works fine for **weaviate 1.18.0** where the following message is returned:
> {"code":401,"message":"anonymous access not enabled, please provide an auth scheme such as OIDC"}

**Comment by antas-marcin** [comment]
> When I submit a GET request to weaviate without the Authorization: Bearer <weaviate-api-key-secret> header set, my request goes through.

Just wanted to clear this, so if you do a `GET <host>/v1` without an authorization header in `v1.18.0` version of Weaviate your request gets blocked (you get `code 401` response) and if you do the same request in `v1.19.0` you get a response yes?

The second thing if do other requests like `GET <host>/v1/schema` or `GET <host>/v1/objects` all of those requests in `v1.18.0` and `v1.19.0` versions get blocked yes? you get `code 401` response, yes?

**Comment by tsafs** [comment]
Yes, that is exactly what happens.

**Comment by antas-marcin** [comment]
The `env settings` approach work properly if you first set the authentication settings in `values.yml` to `false` like so:
```
authentication:
  anonymous_access:
    enabled: false
```
and then set all `authentication` settings using `env variables`:
```
env:
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
  AUTHENTICATION_APIKEY_ENABLED: 'true'
  AUTHENTICATION_APIKEY_USERS: 'irrelevantUserName'
```
