### ISSUE TITLE
storage.fullnameOverride is not working for persistent volume

### ISSUE THREAD

**Issue by shivam1410** [weaviate/weaviate-helm#147]
<img width="557" alt="image" src="https://github.com/weaviate/weaviate-helm/assets/33784139/62e8eb9b-3c0d-4d23-8a99-663af3c54cbf">

pv.yaml

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0109b7cba15479c81
```

storageClass.yaml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
```

claim.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
```
