### ISSUE TITLE
HTTPS with Helm values (GKE)

### ISSUE THREAD

**Issue by eostis** [weaviate/weaviate-helm#153]
Is there a way to add GKE ManagedCertificates to the Helm values?

**Comment by eostis** [comment]
Hi @StefanBogdan,

The main reason is to lower the tech barrier to using Weaviate, especially for small businesses. SSL is difficult to configure, and most/all businesses will refuse to start without.

There are already cloud-specific files, like gcsSecret.yaml for backups. Some more for SSL would not be inconceivable. 

A mix of templates and "gcloud" scripts could be a very strong help at setting the SLL for the cluster namespaces. As far as I know, everything can be scripted with K8S: https://cert-manager.io/docs/tutorials/getting-started-with-cert-manager-on-google-kubernetes-engine-using-lets-encrypt-for-ingress-ssl/

**Comment by jschwanz** [comment]
For me I don't think I'm looking for anything vendor specific. What I would need would be the ability to enable a standard `kind: Ingress` with `metadata.annotations`, `spec.ingressClassName`, 'spec.rules`, and `spec.tls`. Yeah I recognize I can do all of this outside of Helm, but it'd be more convenient to have it all defined and versioned in one configuration.

**Comment by StefanBogdan** [comment]
We are going to explore the option of adding the `Ingress` AND the `cert-manager` to the helm chart. Thanks for the feedback.

**Comment by bryantbiggs** [comment]
I would recommend not adding `cert-manager` to the chart - if you expose Ingress and/or Gateway resources, this should be enough for users to utilize with other resources such as `cert-manager`

**Comment by heresandyboy** [comment]
I had also had trouble when deploying to a KOPS managed cluster in AWS. Without an ingress record provided in the templates I was unable to access Weaviate in our cluster. 

To workaround it I had cloned the `weaviate-helm` repo and copied in an ingress template into the templates folder, and added values for ingress. This is all working nicely for me, but having the ingress built into the chart will help with maintaining this.

In case it offers any assistance to this issue, here is my working ingress template and example values:

**ingressyml**
``` yaml
{{- if .Values.ingress.enabled -}}
{{- $fullName := .Values.service.name -}}
{{- $svcPort := "" -}}
{{- range .Values.service.ports }}
  {{- if eq .name "http" }}
    {{- $svcPort = .port -}}
  {{- end }}
{{- end }}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: helm
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
```

**values passed into helm**
``` yaml
            image:
              tag: 1.20.0
            service:
              name: weaviate
              ports:
                - name: http
                  protocol: TCP
                  port: 80
              type: NodePort
              
            ingress:
              enabled: true
              tls: []
              hosts:
                - host: weaviate.systems.kubernetes.testing.aws.zen.co.uk
                  paths:
                    - path: '/*'
                      pathType: ImplementationSpecific
              annotations:
                kubernetes.io/ingress.class: alb
                alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
                alb.ingress.kubernetes.io/scheme: internal
                alb.ingress.kubernetes.io/backend-protocol: HTTP
                alb.ingress.kubernetes.io/healthcheck-path: /ping
                alb.ingress.kubernetes.io/group.name: weaviate
                external-dns.alpha.kubernetes.io/hostname: weaviate.systems.kubernetes.testing.aws.zen.co.uk
```
