### ISSUE TITLE
If .env_AWS_* defined than env.ENABLE_MODULES is ignored

### ISSUE THREAD

**Issue by RogerSik** [weaviate/weaviate-helm#235]
helm value:
```
          env:
            ENABLE_MODULES: 'backup-s3,text2vec-transformers,qna-transformers'
            BACKUP_S3_BUCKET: 'CHANGE_ME'
```

argocd diff:

<img width="662" alt="15_09-13-13" src="https://github.com/weaviate/weaviate-helm/assets/165814/bb6a941d-de4c-4b07-b656-9e5b21603852">

If: 
```
          env:
            ENABLE_MODULES: 'backup-s3,text2vec-transformers,qna-transformers'
            BACKUP_S3_BUCKET: 'CHANGE_ME'
            AWS_ACCESS_KEY_ID: 'CHANGE_ME'
            AWS_SECRET_ACCESS_KEY: 'CHANGE_ME'
            AWS_REGION: 'CHANGE_ME'
```

then

<img width="652" alt="15_09-13-56" src="https://github.com/weaviate/weaviate-helm/assets/165814/aa241d9f-0377-4d47-8ebc-9ca5b19fbbeb">

Both ENABLE_MODULES value i can confirm with 
```
echo $ENABLE_MODULES 
```

in the container after deployment. ENABLE_MODULES gets always ignored if one of AWS_
 values are defined.

**Comment by RogerSik** [comment]
Found the reason.

If one of 
- env.AWS_ACCESS_KEY_ID 
- env.AWS_SECRET_ACCESS_KEY

is set than env.ENABLE_MODULES is ignored and will be by helm generated. It looks and see
```
          modules:
            text2vec-transformers:
              enabled: true

            qna-transformers:
              enabled: false

          env:
            ENABLE_MODULES: 'backup-s3,text2vec-transformers,qna-transformers' # <-- this gets ignored
```

and ignores the ENABLE_MODULES. We have qna-transformers outside of helm deployed because we coulnd't add 
```
spec:
  template:
    spec:
      runtimeClassName: nvidia
```
to qna-transformers in the helm chart.
