### ISSUE TITLE
Use GOMEMLIMIT and GOMAXPROCS based on the weaviate resource limits

### ISSUE THREAD

**Issue by jfrancoa** [weaviate/weaviate-helm#236]
I came to the following [article](https://blog.howardjohn.info/posts/gomaxprocs/#configuration-in-kubernetes) in which states how to set automatically the GOMEMLIMIT and GOMAXPROCS value depending on the resource.limits defined in the weaviate StatefulSet. 

I did a quick exercise and tried to modify the Weaviate sts to see if it could be applied:
```
kubectl get sts weaviate -o yaml -n weaviate |egrep -A 4 -E "GOMEMLIMIT|GOMAXPROCS|resources"
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.cpu
--
        resources:
          limits:
            cpu: 1500m
            memory: 1500M
        securityContext: {}
```

When passing the GOMEMLIMIT and GOMAXPROCS based on these resource limits, the pod will take automatically the value from the resources:
```
kubectl exec -it weaviate-2 -n weaviate -- sh -c "env | egrep -E 'GOMEMLIMIT|GOMAXPROCS'"
Defaulted container "weaviate" out of: weaviate, configure-sysctl (init)
GOMEMLIMIT=1500000000
GOMAXPROCS=2
```

If by any chance, there are no resources.limits defined in the Weaviate  container from the STS, then it will use the maximum the host can offer:
```
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.cpu
--
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
```
No resources defined, so the pod will take the max:
```
kubectl exec -it weaviate-0 -n weaviate -- sh -c "env | egrep -E 'GOMEMLIMIT|GOMAXPROCS'"
Defaulted container "weaviate" out of: weaviate, configure-sysctl (init)
GOMEMLIMIT=18837078016
GOMAXPROCS=14
```

While, with the current implementation, no GOMEMLIMIT, nor GOMAXPROCS is being defined, as the environment variables aren't being set:
```
kubectl exec -it weaviate-2 -n weaviate -- sh -c "env | egrep -E 'GOMEMLIMIT|GOMAXPROCS'"
Defaulted container "weaviate" out of: weaviate, configure-sysctl (init)
command terminated with exit code 1
```
