### ISSUE TITLE
Allow setting env var which refers to valueFrom

### ISSUE THREAD

**Issue by RogerSik** [weaviate/weaviate-helm#285]
I would like to following values:
```
        env:
        - name: CLUSTER_ADVERTISE_ADDR
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
```

Manually im able to edit the StatefulSet but with helm values this seems no to be possible.
